// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://liifbjpwbhsnoxzcthqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpaWZianB3Ymhzbm94emN0aHF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NDU2NDMsImV4cCI6MjA2NzQyMTY0M30.YE9iQCRkC-4CmkhvIB4XgMNd5Wt1tZKc5h130nhHgQg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});